wandb:
    _target_: sda.utils.loggers.WandbLogger
    save_dir: null #${paths.logs_dir}
    name: ${str:${seed}}
    group: ${name}_${hydra:job.override_dirname}
    # entity: oxcsml
    # entity: cbl-mlg
    entity: emilem
    project: sda
    offline: False
    id: null